// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA312F9sQH8pdX2AdJKpFDG0t7Vgp7ZdDw',
    appId: '1:430155746003:web:dc4bccd810c363de596226',
    messagingSenderId: '430155746003',
    projectId: 'pawanimal-949c2',
    authDomain: 'pawanimal-949c2.firebaseapp.com',
    storageBucket: 'pawanimal-949c2.appspot.com',
    measurementId: 'G-D67CRCH1LL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO1UZfNiy1aEySHflRmdiyDf5Owznc8ZU',
    appId: '1:430155746003:android:ebf049c66d4f950d596226',
    messagingSenderId: '430155746003',
    projectId: 'pawanimal-949c2',
    storageBucket: 'pawanimal-949c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFjfSJBHWRkmkrPb7tvIhg1Cizin3ygcY',
    appId: '1:430155746003:ios:c2cdfbb28d329571596226',
    messagingSenderId: '430155746003',
    projectId: 'pawanimal-949c2',
    storageBucket: 'pawanimal-949c2.appspot.com',
    iosBundleId: 'com.example.paw',
  );
}
